### ISSUE TITLE
Construction of arbitrary number of policies

### ISSUE THREAD

**Issue by cnewman** [srcML/srcSAXEventDispatch#1]
Currently, user has to provide objects for each policy they want to use. This object is how they interact with the policy's parser.

Might be better if we did not require user to provide these objects but constructed them on the fly. Problem is that this means the template needs to construct a number of objects we don't know until compile time. This means recursive template of some sort, perhaps?

**Comment by mjdecker** [comment]
Test suite is adapted and passing.
