### ISSUE TITLE
FunctionPolicy returnType never set

### ISSUE THREAD

**Issue by PJ-Leyden** [srcML/srcSAXEventDispatch#26]
In FunctionPolicySingleEvent, FunctionData has a member 
`TypePolicy::TypeData * returnType;`
For some reason this is never being initialized as the Notify method is never called with a TypePolicy. 
because of this I am unable to print out or retrieve information about class methods and can't include them in the UML diagrams.

**Comment by PJ-Leyden** [comment]
Created a branch to highlight the problem and fix it.

**Comment by mjdecker** [comment]
Good found a problem due to change of how elementStack semantics work.  Actual but is with Function not having the type set correctly.  Class had same problem. I fixed those two.  There is likely more but can be separate issue.

**Comment by mjdecker** [comment]
Done with pull request #27.
