### ISSUE TITLE
General attribute handling

### ISSUE THREAD

**Issue by mjdecker** [srcML/srcSAXEventDispatch#7]
Need a mechanism for handling attributes.

We could create an event for each attribute or each attribute/tag pair.

However, this would only be for the standard attributes.

Extensions with attribute information would not be supported, e.g., stereotypes.

Propose, that we treat the attributes similar to how text is handled.

There is a single event attribute.  The context then has the type and value of the attribute.  I would also suggest having a field for the current tag.  This would be good for both text and attributes.

As an aside, we may want to have an event for unhanded tags that get called.  This would have an additional overhead, and would probably be best as an option.

**Comment by cnewman** [comment]
Attribute solution seems fine to me. Not sure what the last part is saying: 

> As an aside, we may want to have an event for unhanded tags that get called. This would have an additional overhead, and would probably be best as an option.

I'm guessing unhanded is unhandled-- but even then, what tags are unhandled but called?

**Comment by mjdecker** [comment]
Sorry for vagueness.

The use case is someone has transformed a srcML archive and included new tags to the document (ones not generated by srcML).  We may want to generate a generic tag event.  Or perhaps, we could allow them to enable/disable arbitrary tags in the dispatcher.

The first has a lot of overhead which would be better to have it as an option that is off by default.

**Comment by mjdecker** [comment]
Merged.  Once you have read my last comment, this can be closed.

**Comment by cnewman** [comment]
Seems fine to let them add things at their leisure.
